### ISSUE TITLE
Direct list of 952 sampled repositories from study

### ISSUE THREAD

**Issue by akhatami** [sola-st/github-workflow-resource-optimization#1]
I was looking through your dataset and had a question about the repositories used in the study. I'm wondering if there's already a simple way to see the list of 952 repositories that were analyzed?

I found the large data files, but wasn't sure if there's already a straightforward list (like a CSV file) of just these specific repositories somewhere that I might have missed.

If such a list doesn't exist yet, it would be super helpful to have one!

**Comment by akhatami** [comment]
I found a quick  way to extract them like this: 
`df = pd.read_csv("all_runs.csv")`
`repo_handles = df['url'].apply(lambda x: '/'.join(urlparse(x).path.split('/')[2:4])).unique()`

**Comment by michaelpradel** [comment]
Looks like you found a solution, so I'm closing this.
